### ISSUE TITLE
前後の画像に移動できる機能

### ISSUE THREAD

**Issue by radiopunch** [norihitoishida/adjust-images#2]
「最初の画像」「戻る」「次へ」「最後の画像」ボタンを設けて移動できるようにすると配信の終わりに今までの画像を振り返ったりするときに便利かなと思いました。

**Comment by radiopunch** [comment]
ボタンで遷移するよりスクロールで一覧して見れる方が良さそうですかね。

**Comment by norihitoishida** [comment]
> スクロールで一覧して見れる

採用します。ありがとうございます！
